# Generated by Django 3.1.2 on 2020-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.CharField(help_text='latitude of location of the squirrel', max_length=100)),
                ('Longitude', models.CharField(help_text='longitude of location of the squirrel', max_length=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('Shift', models.CharField(blank=True, help_text='AM or PM', max_length=100)),
                ('Date', models.CharField(blank=True, help_text='Date', max_length=100)),
                ('Age', models.CharField(blank=True, help_text='age of the squirrel', max_length=100)),
            ],
        ),
    ]
